title: xSam Solutions
email: engr.leir@gmail.com
description: A blog containing solutions to various problems in the xSam web app.
baseurl: "/xsam-solutions" # the subpath of your site, e.g. /blog
url: "https://engrleir.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: engrleir
github_username:  engrleir

# Allow iframe embedding
webrick:
  headers:
    X-Frame-Options: "ALLOWALL"

# Solution permalink structure
collections:
  solutions:
    output: true
    permalink: /solutions/:name/

defaults:
  - scope:
      type: solutions
    values:
      layout: solution

